ue:
  binary_risk: True
rcc:
  metric_type: scaledrmse
sas:
  question_id: '1_5'
  score_id: 'A_Score'
path:
  save_dir_path: /content/drive/MyDrive/GoogleColab/SA/ShortAnswer/Y15/${sas.question_id}_results/${sas.score_id}