model:
  model_type: 'reg'
  spectral_norm: False
  regularization_metric: False
  regularization_cer: False
ue:
  binary_risk: True
sas:
  prompt_id: 'Y15'
  question_id: '2-3_1_5'
  score_id: 'score'
path:
  save_dir_path: /content/drive/MyDrive/GoogleColab/SA/ShortAnswer/${sas.prompt_id}/${sas.question_id}_results/${sas.score_id}