training:
  fold: 0
  test_size: 0.3
  n_epochs: 30
  batch_size: 8
  learning_rate: 0.00001
  collate_fn: True
  patience: 3
  regularization_metric: False
  regularization_cer: False
model:
  model_name_or_path: 'cl-tohoku/bert-base-japanese'
  reg_or_class: 'ordinal_reg'
  max_length: 512
  id: 0
  num_labels: None
  spectral_norm: False
sas:
  prompt_id: 'Y15'
  question_id: '2-3_1_5'
  score_id: 'score'
  friendly_score: True
path:
  traindata_file_name: /content/drive/MyDrive/GoogleColab/SA/ShortAnswer/${sas.prompt_id}/${sas.question_id}_data/${sas.prompt_id}_${sas.question_id}_fold${training.fold}/train_data.json
  valdata_file_name: /content/drive/MyDrive/GoogleColab/SA/ShortAnswer/${sas.prompt_id}/${sas.question_id}_data/${sas.prompt_id}_${sas.question_id}_fold${training.fold}/dev_data.json
  save_path: /content/drive/MyDrive/GoogleColab//SA/ShortAnswer/${sas.prompt_id}/${sas.question_id}_model/Ord_reg_${sas.score_id}/fold${training.fold}/id${model.id}_org_loss
wandb:
  project: Class_SAS_${sas.question_id}_${sas.score_id}
  project_name: fold${training.fold}_id${model.id}